### ISSUE TITLE
[Feature Request] Log Dates & Rotation

### ISSUE THREAD

**Issue by tronyx** [hotio/autoscan#9]
Would it be possible to log full date stamps rather than just time stamps in the log? Would it also be possible to incorporation some form of log rotation as well?

**Comment by mrhotio** [comment]
Isn't that up to Autoscan?

**Comment by tronyx** [comment]
Yep, sorry. Didn't have enough coffee yet when I made this. Opened one with Autoscan:

https://github.com/Cloudbox/autoscan/issues/75
